version: "3.8"
services:
  ahs:
    image: ghcr.io/system-is/ahs:latest

    ports:
      - 8888:8888

    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    environment:
      DB_HOST: 192.168.157.247
      DB_PORT: 8889
      DB_DBNAME: ahs
      DB_USER: ahs
      DB_PASS: ahsPassword

