version: "3.8"
services:
  ahs:
    image: ghcr.io/system-is/ahs:latest

    ports:
      - 8888:8888

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DBNAME: ahs
      DB_USER: ahs
      DB_PASS: ahsPassword

    depends_on:
      - mysql

  db:
    image: mysql:5.7.38
    ports:
      - 8889:3306

    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/amsdb.cnf:/etc/mysql/conf.d/amsdb.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: ahs
      MYSQL_USER: ahs
      MYSQL_PASSWORD: ahsPassword

volumes:
  mysql:
