version: "3.8"
services:
  ahs:
    image: ghcr.io/system-is/ahs:latest

    ports:
      - 8888:8888

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DBNAME: ahs
      DB_USER: ahs
      DB_PASS: ahsPassword

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.38
    ports:
      - 3306

    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: ahs
      MYSQL_USER: ahs
      DB_PASS: ahsPassword
